### ISSUE TITLE
appsettings.json missing

### ISSUE THREAD

**Issue by asystat** [Prographers/Slack-GPT#4]
Hello,
do you have an example appsettings.json file ?
You reference in the Readme several times but there is no such file. 
Thanks

**Comment by Muchaszewski** [comment]
Sure thing!

Actually there is but inside of the folder with the project, you need to remove Example from the name and all the comments inside of it for it to work!

https://github.com/Prographers/Slack-GPT/blob/main/Slack-GPT-Socket/appsettings.Example.json
